// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TableAjaxEdit.Models.DataModel;

#nullable disable

namespace TableAjaxEdit.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TableAjaxEdit.Models.DataModel.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<double>("Salary")
                        .HasColumnType("float");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Employee");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 11, 23, 15, 33, 11, 54, DateTimeKind.Local).AddTicks(779),
                            Name = "Andrew Peters",
                            Salary = 3500000.0,
                            Status = true
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 11, 23, 15, 33, 11, 54, DateTimeKind.Local).AddTicks(789),
                            Name = "Brice Lambson",
                            Salary = 3600000.0,
                            Status = true
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 11, 23, 15, 33, 11, 54, DateTimeKind.Local).AddTicks(790),
                            Name = "Andrew Johnson",
                            Salary = 5400000.0,
                            Status = true
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 11, 23, 15, 33, 11, 54, DateTimeKind.Local).AddTicks(791),
                            Name = "Rowan Miller",
                            Salary = 5400000.0,
                            Status = true
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 11, 23, 15, 33, 11, 54, DateTimeKind.Local).AddTicks(792),
                            Name = "Michael Peters",
                            Salary = 3500000.0,
                            Status = true
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2023, 11, 23, 15, 33, 11, 54, DateTimeKind.Local).AddTicks(793),
                            Name = "John Miller",
                            Salary = 1600000.0,
                            Status = true
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2023, 11, 23, 15, 33, 11, 54, DateTimeKind.Local).AddTicks(794),
                            Name = "Rowan Baker",
                            Salary = 1400000.0,
                            Status = true
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2023, 11, 23, 15, 33, 11, 54, DateTimeKind.Local).AddTicks(795),
                            Name = "Tom Miller",
                            Salary = 6400000.0,
                            Status = true
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2023, 11, 23, 15, 33, 11, 54, DateTimeKind.Local).AddTicks(797),
                            Name = "Marry Miller",
                            Salary = 1500000.0,
                            Status = true
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2023, 11, 23, 15, 33, 11, 54, DateTimeKind.Local).AddTicks(798),
                            Name = "Harry Miller",
                            Salary = 1400000.0,
                            Status = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
